from enum import StrEnum


class UserAssessmentState(StrEnum):
    WAITING_TOPIC = "WAITING_TOPIC"
    ASKING_QUESTIONS = "ASKING_QUESTIONS"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    WAITING_MANUAL_LEVEL = "WAITING_MANUAL_LEVEL"
    COMPLETED = "COMPLETED"

